### ISSUE TITLE
Create bomber-carrier-app with bomber config in yaml

### ISSUE THREAD

**Issue by ashofthedream** [ashofthedream/loadtest#37]
```yaml
bomber:
  sinks:
    - HistogramSink
    - ashes.of.other.sinks.other.OtherSink
  watchers:
    - Log4jWatcher
    - ashes.of.other.watchers.other.OtherWatcher
  apps:
    include:
      - ashes.of.bomber.example.ExampleApp
      - ashes.of.bomber.another.example.AnotherExampleApp
    build:
      - ashes.of.bomber.builder.example.BuilderExampleAppBuilder
```

- [ ] How to include jars to exists spring-boot-app
- [ ] Add interface for builder apps
